###
POST https://server-sofi.onrender.com/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "RRRR",
  "lastname": "González",
  "age": "23",
  "email": "ZZZZ@gmail.com",
  "studentCode": "A000001",
  "firstQuestion": "Respuesta1",
  "secondQuestion": "Respuesta2",
  "thirdQuestion": "Respuesta3",
  "password": "ZZZZ"
}

###
POST https://server-sofi.onrender.com/api/resources HTTP/1.1
Content-Type: application/json

{
  "name": "web_Prueba3",
  "path": "assets/imgs/resources/internet.png",
  "category": "preposition",
  "icon": "internet",
  "url": "-",
  "state": "0"
}

###
POST https://server-sofi.onrender.com/api/users/check-security-answer HTTP/1.1
Content-Type: application/json

{
  "email": "dgonzalez@autonoma.edu.pe",
  "firstQuestion": "tallarín verde con bisteck",
  "secondQuestion": "Roma",
  "thirdQuestion": "pipoa"
}

###
POST https://server-sofi.onrender.com/api/users/email HTTP/1.1
Content-Type: application/json

{
  "email": "dgonzalez@autonoma.edu.pe"
}



###
POST https://server-sofi.onrender.com/api/users/reset-password HTTP/1.1
Content-Type: application/json

{
  "email": "dgonzalez@autonoma.edu.pe",
  "newPassword": "nueva_contraseña"
}




###
GET https://server-sofi.onrender.com/api/resources HTTP/1.1

###
GET https://server-sofi.onrender.com/api/resources-comprehension HTTP/1.1

###
GET https://server-sofi.onrender.com/api/resources-expression HTTP/1.1

###
GET https://server-sofi.onrender.com/api/resources-comunicationHTTP/1.1

###
GET https://server-sofi.onrender.com/api/resources/comprehension HTTP/1.1

###
GET https://server-sofi.onrender.com/api/resources/communication HTTP/1.1

###
GET https://server-sofi.onrender.com/api/resources/expression HTTP/1.1

###
POST https://server-sofi.onrender.com/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "dgonzalez@autonoma.edu.pe",
  "password": "1234"
}


###
GET https://server-sofi.onrender.com/api/users HTTP/1.1

###
GET https://server-sofi.onrender.com/api/users/651ac5355091a88e3f957968 HTTP/1.1

###
PUT https://server-sofi.onrender.com/api/users/65173b12f08a04139e5f8fce HTTP/1.1
Content-Type: application/json

{
  "name": "Prue ZZZ",
  "lastname": "González",
  "age": "23",
  "email": "prueZ@gmail.com",
  "studentCode": "A000001",
  "firstQuestion": "Respuesta1",
  "secondQuestion": "Respuesta2",
  "thirdQuestion": "Respuesta3",
  "password": "a111"
}

###
DELETE https://server-sofi.onrender.com/api/users/65173a7af08a04139e5f8fc8 HTTP/1.1

###
PUT https://server-sofi.onrender.com/api/resources-state/6521e77350fea23d59ed68df HTTP/1.1
Content-Type: application/json

{
  "state": "0"
}
