###
POST http://localhost:9000/api/communication/create-communication HTTP/1.1
Content-Type: application/json

{
  "id_User": "usuario123",
  "id_Resource": "recurso789",
  "stateResource": "1"
}

###
GET http://localhost:9000/api/communication/list-communication/663108c061904f5584e43522 HTTP/1.1
